export const MOCK_HOTELS: Hotel[] = [
  {
    id: '1',
    name: 'The Ritz-Carlton Dubai',
    images: [
      'https://picsum.photos/400/300?random=21',
      'https://picsum.photos/400/300?random=22',
      'https://picsum.photos/400/300?random=23',
    ],
    starRating: 5,
    reviewRating: 4.0,
    reviewCount: 156,
    roomType: 'PALMSCAPE KING ROOM',
    distanceToCenter: '27.03 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: true,
    },
    price: 194.96,
    currency: '$',
    url: '/hotel/the-ritz-carlton-dubai',
    nightCount: 1,
    adultCount: 2,
  },
  {
    id: '2',
    name: 'Burj Al Arab Jumeirah',
    images: ['https://picsum.photos/400/300?random=24', 'https://picsum.photos/400/300?random=25'],
    starRating: 5,
    reviewRating: 4.8,
    reviewCount: 320,
    roomType: 'OCEAN VIEW SUITE',
    distanceToCenter: '23.03 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: true,
    },
    price: 1250.0,
    currency: '$',
    url: '/hotel/burj-al-arab-jumeirah',
    nightCount: 1,
    adultCount: 2,
  },
  {
    id: '3',
    name: 'Atlantis, The Palm',
    images: [
      'https://picsum.photos/400/300?random=26',
      'https://picsum.photos/400/300?random=27',
      'https://picsum.photos/400/300?random=28',
    ],
    starRating: 5,
    reviewRating: 4.5,
    reviewCount: 890,
    roomType: 'PALM VIEW ROOM',
    distanceToCenter: '15.5 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: false, // Örnek olarak false eklendi
    },
    price: 450.75,
    originalPrice: 550.0,
    currency: '$',
    url: '/hotel/atlantis-the-palm',
    nightCount: 1,
    adultCount: 2,
  },
  {
    id: '4',
    name: 'Address Downtown',
    images: ['https://picsum.photos/400/300?random=29'],
    starRating: 5,
    reviewRating: 4.6,
    reviewCount: 650,
    roomType: 'DELUXE FOUNTAIN VIEW',
    distanceToCenter: '25.0 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: true,
    },
    price: 380.0,
    currency: '$',
    url: '/hotel/address-downtown',
    nightCount: 1,
    adultCount: 2,
  },
]
