export const MOCK_HOTELS: Hotel[] = [
  {
    id: '1',
    name: 'The Ritz-Carlton Dubai',
    images: [
      'https://picsum.photos/400/300?random=21',
      'https://picsum.photos/400/300?random=22',
      'https://picsum.photos/400/300?random=23',
    ],
    starRating: 5,
    reviewRating: 4.0,
    reviewCount: 156,
    roomType: 'PALMSCAPE KING ROOM',
    distanceToCenter: '27.03 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: true,
    },
    price: 194.96,
    currency: '$',
    url: '/hotel/the-ritz-carlton-dubai',
    nightCount: 1,
    adultCount: 2,
  },
  {
    id: '2',
    name: 'Burj Al Arab Jumeirah',
    images: ['https://picsum.photos/400/300?random=24', 'https://picsum.photos/400/300?random=25'],
    starRating: 5,
    reviewRating: 4.8,
    reviewCount: 320,
    roomType: 'OCEAN VIEW SUITE',
    distanceToCenter: '23.03 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: true,
    },
    price: 1250.0,
    currency: '$',
    url: '/hotel/burj-al-arab-jumeirah',
    nightCount: 1,
    adultCount: 2,
  },
  {
    id: '3',
    name: 'Atlantis, The Palm',
    images: [
      'https://picsum.photos/400/300?random=26',
      'https://picsum.photos/400/300?random=27',
      'https://picsum.photos/400/300?random=28',
    ],
    starRating: 5,
    reviewRating: 4.5,
    reviewCount: 890,
    roomType: 'PALM VIEW ROOM',
    distanceToCenter: '15.5 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: false, // Örnek olarak false eklendi
    },
    price: 450.75,
    originalPrice: 550.0,
    currency: '$',
    url: '/hotel/atlantis-the-palm',
    nightCount: 1,
    adultCount: 2,
  },
  {
    id: '4',
    name: 'Address Downtown',
    images: ['https://picsum.photos/400/300?random=29'],
    starRating: 5,
    reviewRating: 4.6,
    reviewCount: 650,
    roomType: 'DELUXE FOUNTAIN VIEW',
    distanceToCenter: '25.0 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: true,
    },
    price: 380.0,
    currency: '$',
    url: '/hotel/address-downtown',
    nightCount: 1,
    adultCount: 2,
  },
  {
    id: '5',
    name: 'Mandarin Oriental Jumeira',
    images: [
      'https://picsum.photos/400/300?random=30',
      'https://picsum.photos/400/300?random=31',
      'https://picsum.photos/400/300?random=32',
    ],
    starRating: 5,
    reviewRating: 4.7,
    reviewCount: 410,
    roomType: 'SEAVIEW ROOM',
    distanceToCenter: '20.0 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: true,
    },
    price: 599.99,
    currency: '$',
    url: '/hotel/mandarin-oriental-jumeira',
    nightCount: 1,
    adultCount: 2,
  },
  {
    id: '6',
    name: 'Jumeirah Emirates Towers',
    images: ['https://picsum.photos/400/300?random=33', 'https://picsum.photos/400/300?random=34'],
    starRating: 5,
    reviewRating: 4.3,
    reviewCount: 512,
    roomType: 'DELUXE ROOM',
    distanceToCenter: '10.0 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: true,
    },
    price: 299.99,
    currency: '$',
    url: '/hotel/jumeirah-emirates-towers',
    nightCount: 1,
    adultCount: 2,
  },
  {
    id: '7',
    name: 'Sofitel Dubai The Palm',
    images: ['https://picsum.photos/400/300?random=35', 'https://picsum.photos/400/300?random=36'],
    starRating: 5,
    reviewRating: 4.2,
    reviewCount: 340,
    roomType: 'LUXURY SEA VIEW ROOM',
    distanceToCenter: '8.3 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: false,
    },
    price: 400.0,
    currency: '$',
    url: '/hotel/sofitel-dubai-the-palm',
    nightCount: 1,
    adultCount: 2,
  },
  {
    id: '8',
    name: 'Fairmont The Palm',
    images: [
      'https://picsum.photos/400/300?random=37',
      'https://picsum.photos/400/300?random=38',
      'https://picsum.photos/400/300?random=39',
    ],
    starRating: 5,
    reviewRating: 4.4,
    reviewCount: 290,
    roomType: 'FAIRMONT DELUXE ROOM',
    distanceToCenter: '12.5 km',
    features: {
      breakfast: true,
      forTwoPeople: true,
      freeCancellation: true,
    },
    price: 350.5,
    currency: '$',
    url: '/hotel/fairmont-the-palm',
    nightCount: 1,
    adultCount: 2,
  },
]
