export const ICONIC_PLACES: IconicPlaces[] = [
  {
    id: '1',
    rank: 1,
    title: 'Most popular activities',
    description: ['1 - 3 saat', 'Küçük grup', 'İsteğe bağlı sesli rehber'],
    images: [
      'https://picsum.photos/400/300?random=1',
      'https://picsum.photos/400/300?random=2',
      'https://picsum.photos/400/300?random=3',
    ],
    rating: 4.0,
    reviewCount: 156,
    price: 194.96,
    duration: '1 - 3 hours',
    groupInfo: 'Small group',
    features: ['Audio guide included'],
    isPopular: true,
    purchaseCount: 100,
  },
  {
    id: '2',
    rank: 2,
    title: 'Abu Dhabi İkonik Yerler Turu',
    description: ['Tam gün', 'Orta grup', 'Otel transferi dahil'],
    images: ['https://picsum.photos/400/300?random=4', 'https://picsum.photos/400/300?random=5'],
    rating: 4.0,
    reviewCount: 156,
    price: 194.96,
    duration: 'Full day',
    groupInfo: 'Medium group',
    features: ['Hotel pickup included'],
    purchaseCount: 100,
  },
  {
    id: '3',
    rank: 3,
    title: 'Dubai Özel Şoförlü VIP İkonik Yerler Turu',
    description: ['6 saat', 'Özel', 'Sesli rehber dahil', 'Otel transferi dahil'],
    images: [
      'https://picsum.photos/400/300?random=6',
      'https://picsum.photos/400/300?random=7',
      'https://picsum.photos/400/300?random=8',
      'https://picsum.photos/400/300?random=9',
    ],
    rating: 4.0,
    reviewCount: 156,
    price: 194.96,
    originalPrice: 250.0,
    duration: '6 hours',
    groupInfo: 'Private',
    features: ['Audio guide included', 'Hotel pickup included'],
    purchaseCount: 100,
  },
  {
    id: '4',
    rank: 4,
    title: 'Dubai Çöl Safari Turu',
    description: ['6 saat', 'Büyük grup', 'Otel transferi dahil'],
    images: ['https://picsum.photos/400/300?random=10', 'https://picsum.photos/400/300?random=11'],
    rating: 4.0,
    reviewCount: 156,
    price: 194.96,
    duration: '6 hours',
    groupInfo: 'Large group',
    features: ['Hotel pickup included'],
    purchaseCount: 100,
  },
]
