export const MOCK_POPULAR_ACTIVITIES: ActivityCard[] = [
  {
    id: '1',
    title: 'Legoland Tema Parkı',
    description: 'Özel Kabin • Ücretsiz İkramlar',
    images: [
      'https://picsum.photos/400/600?random=101',
      'https://picsum.photos/400/600?random=102',
    ],
    rating: 4.0,
    reviewCount: 156,
    price: 194.96,
    originalPrice: 250.96,
    currency: '$',
    hasDiscount: true,
    discountPercentage: 22,
  },
  {
    id: '2',
    title: "Skydive Dubai: The Palm Drop Zone'da Tandem Skydiving Deneyimi...",
    description: 'Özel Kabin • Ücretsiz İkramlar',
    images: [
      'https://picsum.photos/400/600?random=103',
      'https://picsum.photos/400/600?random=104',
    ],
    rating: 4.0,
    reviewCount: 156,
    price: 194.96,
    originalPrice: 250.96,
    currency: '$',
    hasDiscount: true,
    discountPercentage: 22,
  },
  {
    id: '3',
    title: 'Legoland Tema Parkı',
    description: 'Özel Kabin • Ücretsiz İkramlar',
    images: [
      'https://picsum.photos/400/600?random=105',
      'https://picsum.photos/400/600?random=106',
    ],
    rating: 4.0,
    reviewCount: 156,
    price: 194.96,
    originalPrice: 250.96,
    currency: '$',
    hasDiscount: true,
    discountPercentage: 22,
  },
  {
    id: '4',
    title: 'Burj El Arab',
    description: 'Özel Kabin • Ücretsiz İkramlar',
    images: [
      'https://picsum.photos/400/600?random=107',
      'https://picsum.photos/400/600?random=108',
    ],
    rating: 4.0,
    reviewCount: 156,
    price: 194.96,
    originalPrice: 250.96,
    currency: '$',
    hasDiscount: true,
    discountPercentage: 22,
  },
]
