export const MOCK_RENT_A_CAR: RentACar[] = [
  {
    id: '1',
    brand: 'Chevrolet',
    model: 'Camaro',
    year: 2024,
    category: 'Luxury',
    images: [
      'https://picsum.photos/400/300?random=31',
      'https://picsum.photos/400/300?random=32',
      'https://picsum.photos/400/300?random=33',
    ],
    rating: 4.0,
    reviewCount: 156,
    pricePerDay: 194.96,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 4,
      fuelType: 'Petrol',
      bluetooth: true,
      gps: true,
      unlimitedMileage: true,
      insurance: true,
    },
    location: 'Al Barsha Rd - al Barsha - al Barsha 1, Dubai',
    distanceFromCenter: '12.4 km',
    availability: true,
    fuelPolicy: 'Full to Full',
    pickupLocations: ['Dubai Airport', 'Dubai Mall', 'Downtown Dubai'],
    supplier: 'Enterprise',
    isPopular: true,
  },
  {
    id: '2',
    brand: 'BMW',
    model: 'X1',
    year: 2024,
    category: 'SUV',
    images: ['https://picsum.photos/400/300?random=34', 'https://picsum.photos/400/300?random=35'],
    rating: 4.0,
    reviewCount: 156,
    pricePerDay: 194.96,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 4,
      fuelType: 'Petrol',
      bluetooth: true,
      gps: true,
      unlimitedMileage: true,
      insurance: true,
    },
    location: 'Al Barsha Rd - al Barsha - al Barsha 1, Dubai',
    distanceFromCenter: '12.4 km',
    availability: true,
    fuelPolicy: 'Full to Full',
    pickupLocations: ['Dubai Airport', 'Dubai Mall'],
    supplier: 'Hertz',
  },
  {
    id: '3',
    brand: 'Cadillac',
    model: 'Escalade 600',
    year: 2024,
    category: 'Luxury',
    images: [
      'https://picsum.photos/400/300?random=36',
      'https://picsum.photos/400/300?random=37',
      'https://picsum.photos/400/300?random=38',
    ],
    rating: 4.0,
    reviewCount: 156,
    pricePerDay: 194.96,
    originalPricePerDay: 250.0,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 4,
      fuelType: 'Petrol',
      bluetooth: true,
      gps: true,
      unlimitedMileage: true,
      insurance: true,
    },
    location: 'Al Barsha Rd - al Barsha - al Barsha 1, Dubai',
    distanceFromCenter: '12.4 km',
    availability: true,
    fuelPolicy: 'Full to Full',
    pickupLocations: ['Dubai Airport', 'Dubai Mall', 'Downtown Dubai', 'Marina'],
    supplier: 'Avis',
  },
  {
    id: '4',
    brand: 'Chevrolet',
    model: 'Camaro',
    year: 2024,
    category: 'Luxury',
    images: ['https://picsum.photos/400/300?random=39', 'https://picsum.photos/400/300?random=40'],
    rating: 4.0,
    reviewCount: 156,
    pricePerDay: 194.96,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 4,
      fuelType: 'Petrol',
      bluetooth: true,
      gps: true,
      unlimitedMileage: true,
      insurance: true,
    },
    location: 'Al Barsha Rd - al Barsha - al Barsha 1, Dubai',
    distanceFromCenter: '12.4 km',
    availability: true,
    fuelPolicy: 'Full to Full',
    pickupLocations: ['Dubai Airport', 'Downtown Dubai'],
    supplier: 'Budget',
  },
]
