export const MOCK_RENT_A_CAR: RentACar[] = [
  {
    id: '1',
    brand: 'Chevrolet',
    model: 'Camaro',
    year: 2024,
    category: 'Luxury',
    images: [
      'https://picsum.photos/400/300?random=31',
      'https://picsum.photos/400/300?random=32',
      'https://picsum.photos/400/300?random=33',
    ],
    rating: 4.0,
    reviewCount: 156,
    pricePerDay: 194.96,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 4,
      fuelType: 'Petrol',
      bluetooth: true,
      gps: true,
      unlimitedMileage: true,
      insurance: true,
    },
    location: 'Al Barsha Rd - al Barsha - al Barsha 1, Dubai',
    distanceFromCenter: '12.4 km',
    availability: true,
    fuelPolicy: 'Full to Full',
    pickupLocations: ['Dubai Airport', 'Dubai Mall', 'Downtown Dubai'],
    supplier: 'Enterprise',
    isPopular: true,
  },
  {
    id: '2',
    brand: 'BMW',
    model: 'X1',
    year: 2024,
    category: 'SUV',
    images: ['https://picsum.photos/400/300?random=34', 'https://picsum.photos/400/300?random=35'],
    rating: 4.0,
    reviewCount: 156,
    pricePerDay: 194.96,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 4,
      fuelType: 'Petrol',
      bluetooth: true,
      gps: true,
      unlimitedMileage: true,
      insurance: true,
    },
    location: 'Al Barsha Rd - al Barsha - al Barsha 1, Dubai',
    distanceFromCenter: '12.4 km',
    availability: true,
    fuelPolicy: 'Full to Full',
    pickupLocations: ['Dubai Airport', 'Dubai Mall'],
    supplier: 'Hertz',
  },
  {
    id: '3',
    brand: 'Cadillac',
    model: 'Escalade 600',
    year: 2024,
    category: 'Luxury',
    images: [
      'https://picsum.photos/400/300?random=36',
      'https://picsum.photos/400/300?random=37',
      'https://picsum.photos/400/300?random=38',
    ],
    rating: 4.0,
    reviewCount: 156,
    pricePerDay: 194.96,
    originalPricePerDay: 250.0,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 4,
      fuelType: 'Petrol',
      bluetooth: true,
      gps: true,
      unlimitedMileage: true,
      insurance: true,
    },
    location: 'Al Barsha Rd - al Barsha - al Barsha 1, Dubai',
    distanceFromCenter: '12.4 km',
    availability: true,
    fuelPolicy: 'Full to Full',
    pickupLocations: ['Dubai Airport', 'Dubai Mall', 'Downtown Dubai', 'Marina'],
    supplier: 'Avis',
  },
  {
    id: '4',
    brand: 'Chevrolet',
    model: 'Camaro',
    year: 2024,
    category: 'Luxury',
    images: ['https://picsum.photos/400/300?random=39', 'https://picsum.photos/400/300?random=40'],
    rating: 4.0,
    reviewCount: 156,
    pricePerDay: 194.96,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 4,
      fuelType: 'Petrol',
      bluetooth: true,
      gps: true,
      unlimitedMileage: true,
      insurance: true,
    },
    location: 'Al Barsha Rd - al Barsha - al Barsha 1, Dubai',
    distanceFromCenter: '12.4 km',
    availability: true,
    fuelPolicy: 'Full to Full',
    pickupLocations: ['Dubai Airport', 'Downtown Dubai'],
    supplier: 'Budget',
  },
  {
    id: '5',
    brand: 'Ford',
    model: 'Fiesta',
    year: 2024,
    category: 'Economy',
    images: ['https://picsum.photos/400/300?random=41', 'https://picsum.photos/400/300?random=42'],
    rating: 4.2,
    reviewCount: 110,
    pricePerDay: 55.2,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: false,
      seats: 5,
      fuelType: 'Petrol',
      bluetooth: true,
      gps: false,
      unlimitedMileage: true,
      insurance: true,
    },
    location: 'Downtown Dubai, Dubai',
    distanceFromCenter: '5.0 km',
    availability: true,
    fuelPolicy: 'Same to Same',
    pickupLocations: ['Dubai Airport', 'Downtown Dubai'],
    supplier: 'Thrifty',
  },
  {
    id: '6',
    brand: 'Toyota',
    model: 'Prius',
    year: 2024,
    category: 'Hybrid',
    images: ['https://picsum.photos/400/300?random=43', 'https://picsum.photos/400/300?random=44'],
    rating: 3.8,
    reviewCount: 76,
    pricePerDay: 65.0,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 4,
      fuelType: 'Hybrid',
      bluetooth: true,
      gps: true,
      unlimitedMileage: false,
      insurance: true,
    },
    location: 'Dubai Marina, Dubai',
    distanceFromCenter: '15.0 km',
    availability: false,
    fuelPolicy: 'Full to Full',
    pickupLocations: ['Dubai Marina', 'Dubai Mall'],
    supplier: 'Green Motion',
    isPopular: true,
  },
  {
    id: '7',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2024,
    category: 'Convertible',
    images: ['https://picsum.photos/400/300?random=45', 'https://picsum.photos/400/300?random=46'],
    rating: 4.5,
    reviewCount: 200,
    pricePerDay: 120.5,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 4,
      fuelType: 'Electric',
      bluetooth: true,
      gps: true,
      unlimitedMileage: true,
      insurance: true,
    },
    location: 'Palm Jumeirah, Dubai',
    distanceFromCenter: '20.0 km',
    availability: true,
    fuelPolicy: 'Pre-purchase',
    pickupLocations: ['Palm Jumeirah', 'Dubai Airport'],
    supplier: 'Elon Rentals',
    isPopular: true,
  },
  {
    id: '8',
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2024,
    category: 'Compact',
    images: ['https://picsum.photos/400/300?random=47', 'https://picsum.photos/400/300?random=48'],
    rating: 3.9,
    reviewCount: 130,
    pricePerDay: 75.0,
    currency: '$',
    features: {
      airConditioning: true,
      automaticTransmission: true,
      seats: 5,
      fuelType: 'Diesel',
      bluetooth: true,
      gps: true,
      unlimitedMileage: false,
      insurance: true,
    },
    location: 'Deira, Dubai',
    distanceFromCenter: '7.5 km',
    availability: true,
    fuelPolicy: 'Same to Same',
    pickupLocations: ['Deira City Center', 'Dubai Mall'],
    supplier: 'Europcar',
  },
]
