export const MOCK_TOURS: Tour[] = [
  {
    id: '1',
    title: 'Dubai Helicopter Turu',
    description: 'Özel Kabin • Ücretsiz İkramlar',
    images: [
      'https://picsum.photos/400/600?random=201',
      'https://picsum.photos/400/600?random=202',
    ],
    rating: 4.0,
    reviewCount: 156,
    price: 250.96,
    currency: '$',
    priceNote: '/ kişi başı',
  },
  {
    id: '2',
    title: 'Çölde 4x4 ile Safari',
    description: 'Özel Kabin • Ücretsiz İkramlar',
    images: ['https://picsum.photos/400/600?random=203'],
    rating: 4.0,
    reviewCount: 156,
    price: 60.96,
    currency: '$',
    priceNote: '/ kişi başı',
  },
  {
    id: '3',
    title: 'Abu Dhabi İkonik Yerler Turu',
    description: 'Özel Kabin • Ücretsiz İkramlar',
    images: ['https://picsum.photos/400/600?random=204'],
    rating: 4.0,
    reviewCount: 156,
    price: 50.96,
    currency: '$',
    priceNote: '/ kişi başı',
  },
  {
    id: '4',
    title: 'Dubai Çöl Safari Turu',
    description: 'Özel Kabin • Ücretsiz İkramlar',
    images: ['https://picsum.photos/400/600?random=205'],
    rating: 4.0,
    reviewCount: 156,
    price: 150.96,
    currency: '$',
    priceNote: '/ kişi başı',
  },
]
