export const MOCK_YACHTS: Yacht[] = [
  {
    id: '1',
    name: 'Symphony Yat',
    images: [
      'https://picsum.photos/400/300?random=301',
      'https://picsum.photos/400/300?random=302',
      'https://picsum.photos/400/300?random=303',
    ],
    rating: 4.0,
    reviewCount: 156,
    location: 'Dubai limanı, Berth AH6',
    rentalDuration: '1 Saat',
    capacity: 4,
    price: 176.96,
    currency: '$',
    priceNote: '/ kişi başı',
  },
  {
    id: '2',
    name: 'Symphony Yat',
    images: [
      'https://picsum.photos/400/300?random=304',
      'https://picsum.photos/400/300?random=305',
    ],
    rating: 4.0,
    reviewCount: 156,
    location: 'Dubai limanı, Berth AH6',
    rentalDuration: '1 Saat',
    capacity: 4,
    price: 176.96,
    currency: '$',
    priceNote: '/ kişi başı',
  },
  {
    id: '3',
    name: 'Symphony Yat',
    images: [
      'https://picsum.photos/400/300?random=306',
      'https://picsum.photos/400/300?random=307',
    ],
    rating: 4.0,
    reviewCount: 156,
    location: 'Dubai limanı, Berth AH6',
    rentalDuration: '1 Saat',
    capacity: 4,
    price: 176.96,
    currency: '$',
    priceNote: '/ kişi başı',
  },
  {
    id: '4',
    name: 'Symphony Yat',
    images: ['https://picsum.photos/400/300?random=308'],
    rating: 4.0,
    reviewCount: 156,
    location: 'Dubai limanı, Berth AH6',
    rentalDuration: '1 Saat',
    capacity: 4,
    price: 176.96,
    currency: '$',
    priceNote: '/ kişi başı',
  },
]
