/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangPendingRouteImport } from './routes/$lang/pending'
import { Route as LangNotFoundRouteImport } from './routes/$lang/not-found'
import { Route as LangErrorRouteImport } from './routes/$lang/error'
import { Route as LangPublicRouteRouteImport } from './routes/$lang/_public/route'
import { Route as LangPublicIndexRouteImport } from './routes/$lang/_public/index'
import { Route as LangPublicYachtRouteRouteImport } from './routes/$lang/_public/yacht.route'
import { Route as LangPublicRentACarRouteRouteImport } from './routes/$lang/_public/rent-a-car.route'
import { Route as LangPublicHotelsRouteRouteImport } from './routes/$lang/_public/hotels.route'
import { Route as LangPublicFlightsRouteRouteImport } from './routes/$lang/_public/flights.route'
import { Route as LangPublicActivitiesRouteRouteImport } from './routes/$lang/_public/activities.route'
import { Route as LangPublicYachtIndexRouteImport } from './routes/$lang/_public/yacht.index'
import { Route as LangPublicTransferIndexRouteImport } from './routes/$lang/_public/transfer.index'
import { Route as LangPublicToursIndexRouteImport } from './routes/$lang/_public/tours.index'
import { Route as LangPublicSafariTourIndexRouteImport } from './routes/$lang/_public/safari-tour.index'
import { Route as LangPublicRentACarIndexRouteImport } from './routes/$lang/_public/rent-a-car.index'
import { Route as LangPublicHotelsIndexRouteImport } from './routes/$lang/_public/hotels.index'
import { Route as LangPublicGuideIndexRouteImport } from './routes/$lang/_public/guide.index'
import { Route as LangPublicFlightsIndexRouteImport } from './routes/$lang/_public/flights.index'
import { Route as LangPublicActivitiesIndexRouteImport } from './routes/$lang/_public/activities.index'
import { Route as LangPublicYachtSearchRouteImport } from './routes/$lang/_public/yacht.search'
import { Route as LangPublicHotelsSearchRouteImport } from './routes/$lang/_public/hotels.search'
import { Route as LangPublicGuideVisaRouteImport } from './routes/$lang/_public/guide.visa'
import { Route as LangPublicGuideSimCardRouteImport } from './routes/$lang/_public/guide.sim-card'
import { Route as LangPublicGuideRestaurantsRouteImport } from './routes/$lang/_public/guide.restaurants'
import { Route as LangPublicGuideHospitalsRouteImport } from './routes/$lang/_public/guide.hospitals'
import { Route as LangPublicGuideBundlesRouteImport } from './routes/$lang/_public/guide.bundles'
import { Route as LangPublicFlightsSearchRouteImport } from './routes/$lang/_public/flights.search'
import { Route as LangPublicActivitiesSearchRouteImport } from './routes/$lang/_public/activities.search'
import { Route as LangPublicRentACarSearchRouteRouteImport } from './routes/$lang/_public/rent-a-car.search.route'
import { Route as LangPublicRentACarSelectIndexRouteImport } from './routes/$lang/_public/rent-a-car.select.index'
import { Route as LangPublicRentACarSearchIndexRouteImport } from './routes/$lang/_public/rent-a-car.search.index'
import { Route as LangPublicRentACarSelectSlugRouteImport } from './routes/$lang/_public/rent-a-car.select.$slug'
import { ServerRoute as SitemapDotxmlServerRouteImport } from './routes/sitemap[.]xml'
import { ServerRoute as RssDotxmlServerRouteImport } from './routes/rss[.]xml'
import { ServerRoute as RobotsDottxtServerRouteImport } from './routes/robots[.]txt'

const LangRouteImport = createFileRoute('/$lang')()
const rootServerRouteImport = createServerRootRoute()

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPendingRoute = LangPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => LangRoute,
} as any)
const LangNotFoundRoute = LangNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => LangRoute,
} as any)
const LangErrorRoute = LangErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => LangRoute,
} as any)
const LangPublicRouteRoute = LangPublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => LangRoute,
} as any)
const LangPublicIndexRoute = LangPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicYachtRouteRoute = LangPublicYachtRouteRouteImport.update({
  id: '/yacht',
  path: '/yacht',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicRentACarRouteRoute = LangPublicRentACarRouteRouteImport.update({
  id: '/rent-a-car',
  path: '/rent-a-car',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicHotelsRouteRoute = LangPublicHotelsRouteRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicFlightsRouteRoute = LangPublicFlightsRouteRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicActivitiesRouteRoute =
  LangPublicActivitiesRouteRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => LangPublicRouteRoute,
  } as any)
const LangPublicYachtIndexRoute = LangPublicYachtIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangPublicYachtRouteRoute,
} as any)
const LangPublicTransferIndexRoute = LangPublicTransferIndexRouteImport.update({
  id: '/transfer/',
  path: '/transfer/',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicToursIndexRoute = LangPublicToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicSafariTourIndexRoute =
  LangPublicSafariTourIndexRouteImport.update({
    id: '/safari-tour/',
    path: '/safari-tour/',
    getParentRoute: () => LangPublicRouteRoute,
  } as any)
const LangPublicRentACarIndexRoute = LangPublicRentACarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangPublicRentACarRouteRoute,
} as any)
const LangPublicHotelsIndexRoute = LangPublicHotelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangPublicHotelsRouteRoute,
} as any)
const LangPublicGuideIndexRoute = LangPublicGuideIndexRouteImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicFlightsIndexRoute = LangPublicFlightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangPublicFlightsRouteRoute,
} as any)
const LangPublicActivitiesIndexRoute =
  LangPublicActivitiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangPublicActivitiesRouteRoute,
  } as any)
const LangPublicYachtSearchRoute = LangPublicYachtSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LangPublicYachtRouteRoute,
} as any)
const LangPublicHotelsSearchRoute = LangPublicHotelsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LangPublicHotelsRouteRoute,
} as any)
const LangPublicGuideVisaRoute = LangPublicGuideVisaRouteImport.update({
  id: '/guide/visa',
  path: '/guide/visa',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicGuideSimCardRoute = LangPublicGuideSimCardRouteImport.update({
  id: '/guide/sim-card',
  path: '/guide/sim-card',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicGuideRestaurantsRoute =
  LangPublicGuideRestaurantsRouteImport.update({
    id: '/guide/restaurants',
    path: '/guide/restaurants',
    getParentRoute: () => LangPublicRouteRoute,
  } as any)
const LangPublicGuideHospitalsRoute =
  LangPublicGuideHospitalsRouteImport.update({
    id: '/guide/hospitals',
    path: '/guide/hospitals',
    getParentRoute: () => LangPublicRouteRoute,
  } as any)
const LangPublicGuideBundlesRoute = LangPublicGuideBundlesRouteImport.update({
  id: '/guide/bundles',
  path: '/guide/bundles',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicFlightsSearchRoute = LangPublicFlightsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LangPublicFlightsRouteRoute,
} as any)
const LangPublicActivitiesSearchRoute =
  LangPublicActivitiesSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => LangPublicActivitiesRouteRoute,
  } as any)
const LangPublicRentACarSearchRouteRoute =
  LangPublicRentACarSearchRouteRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => LangPublicRentACarRouteRoute,
  } as any)
const LangPublicRentACarSelectIndexRoute =
  LangPublicRentACarSelectIndexRouteImport.update({
    id: '/select/',
    path: '/select/',
    getParentRoute: () => LangPublicRentACarRouteRoute,
  } as any)
const LangPublicRentACarSearchIndexRoute =
  LangPublicRentACarSearchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangPublicRentACarSearchRouteRoute,
  } as any)
const LangPublicRentACarSelectSlugRoute =
  LangPublicRentACarSelectSlugRouteImport.update({
    id: '/select/$slug',
    path: '/select/$slug',
    getParentRoute: () => LangPublicRentACarRouteRoute,
  } as any)
const SitemapDotxmlServerRoute = SitemapDotxmlServerRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootServerRouteImport,
} as any)
const RssDotxmlServerRoute = RssDotxmlServerRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootServerRouteImport,
} as any)
const RobotsDottxtServerRoute = RobotsDottxtServerRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangPublicRouteRouteWithChildren
  '/$lang/error': typeof LangErrorRoute
  '/$lang/not-found': typeof LangNotFoundRoute
  '/$lang/pending': typeof LangPendingRoute
  '/$lang/activities': typeof LangPublicActivitiesRouteRouteWithChildren
  '/$lang/flights': typeof LangPublicFlightsRouteRouteWithChildren
  '/$lang/hotels': typeof LangPublicHotelsRouteRouteWithChildren
  '/$lang/rent-a-car': typeof LangPublicRentACarRouteRouteWithChildren
  '/$lang/yacht': typeof LangPublicYachtRouteRouteWithChildren
  '/$lang/': typeof LangPublicIndexRoute
  '/$lang/rent-a-car/search': typeof LangPublicRentACarSearchRouteRouteWithChildren
  '/$lang/activities/search': typeof LangPublicActivitiesSearchRoute
  '/$lang/flights/search': typeof LangPublicFlightsSearchRoute
  '/$lang/guide/bundles': typeof LangPublicGuideBundlesRoute
  '/$lang/guide/hospitals': typeof LangPublicGuideHospitalsRoute
  '/$lang/guide/restaurants': typeof LangPublicGuideRestaurantsRoute
  '/$lang/guide/sim-card': typeof LangPublicGuideSimCardRoute
  '/$lang/guide/visa': typeof LangPublicGuideVisaRoute
  '/$lang/hotels/search': typeof LangPublicHotelsSearchRoute
  '/$lang/yacht/search': typeof LangPublicYachtSearchRoute
  '/$lang/activities/': typeof LangPublicActivitiesIndexRoute
  '/$lang/flights/': typeof LangPublicFlightsIndexRoute
  '/$lang/guide': typeof LangPublicGuideIndexRoute
  '/$lang/hotels/': typeof LangPublicHotelsIndexRoute
  '/$lang/rent-a-car/': typeof LangPublicRentACarIndexRoute
  '/$lang/safari-tour': typeof LangPublicSafariTourIndexRoute
  '/$lang/tours': typeof LangPublicToursIndexRoute
  '/$lang/transfer': typeof LangPublicTransferIndexRoute
  '/$lang/yacht/': typeof LangPublicYachtIndexRoute
  '/$lang/rent-a-car/select/$slug': typeof LangPublicRentACarSelectSlugRoute
  '/$lang/rent-a-car/search/': typeof LangPublicRentACarSearchIndexRoute
  '/$lang/rent-a-car/select': typeof LangPublicRentACarSelectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangPublicIndexRoute
  '/$lang/error': typeof LangErrorRoute
  '/$lang/not-found': typeof LangNotFoundRoute
  '/$lang/pending': typeof LangPendingRoute
  '/$lang/activities/search': typeof LangPublicActivitiesSearchRoute
  '/$lang/flights/search': typeof LangPublicFlightsSearchRoute
  '/$lang/guide/bundles': typeof LangPublicGuideBundlesRoute
  '/$lang/guide/hospitals': typeof LangPublicGuideHospitalsRoute
  '/$lang/guide/restaurants': typeof LangPublicGuideRestaurantsRoute
  '/$lang/guide/sim-card': typeof LangPublicGuideSimCardRoute
  '/$lang/guide/visa': typeof LangPublicGuideVisaRoute
  '/$lang/hotels/search': typeof LangPublicHotelsSearchRoute
  '/$lang/yacht/search': typeof LangPublicYachtSearchRoute
  '/$lang/activities': typeof LangPublicActivitiesIndexRoute
  '/$lang/flights': typeof LangPublicFlightsIndexRoute
  '/$lang/guide': typeof LangPublicGuideIndexRoute
  '/$lang/hotels': typeof LangPublicHotelsIndexRoute
  '/$lang/rent-a-car': typeof LangPublicRentACarIndexRoute
  '/$lang/safari-tour': typeof LangPublicSafariTourIndexRoute
  '/$lang/tours': typeof LangPublicToursIndexRoute
  '/$lang/transfer': typeof LangPublicTransferIndexRoute
  '/$lang/yacht': typeof LangPublicYachtIndexRoute
  '/$lang/rent-a-car/select/$slug': typeof LangPublicRentACarSelectSlugRoute
  '/$lang/rent-a-car/search': typeof LangPublicRentACarSearchIndexRoute
  '/$lang/rent-a-car/select': typeof LangPublicRentACarSelectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/_public': typeof LangPublicRouteRouteWithChildren
  '/$lang/error': typeof LangErrorRoute
  '/$lang/not-found': typeof LangNotFoundRoute
  '/$lang/pending': typeof LangPendingRoute
  '/$lang/_public/activities': typeof LangPublicActivitiesRouteRouteWithChildren
  '/$lang/_public/flights': typeof LangPublicFlightsRouteRouteWithChildren
  '/$lang/_public/hotels': typeof LangPublicHotelsRouteRouteWithChildren
  '/$lang/_public/rent-a-car': typeof LangPublicRentACarRouteRouteWithChildren
  '/$lang/_public/yacht': typeof LangPublicYachtRouteRouteWithChildren
  '/$lang/_public/': typeof LangPublicIndexRoute
  '/$lang/_public/rent-a-car/search': typeof LangPublicRentACarSearchRouteRouteWithChildren
  '/$lang/_public/activities/search': typeof LangPublicActivitiesSearchRoute
  '/$lang/_public/flights/search': typeof LangPublicFlightsSearchRoute
  '/$lang/_public/guide/bundles': typeof LangPublicGuideBundlesRoute
  '/$lang/_public/guide/hospitals': typeof LangPublicGuideHospitalsRoute
  '/$lang/_public/guide/restaurants': typeof LangPublicGuideRestaurantsRoute
  '/$lang/_public/guide/sim-card': typeof LangPublicGuideSimCardRoute
  '/$lang/_public/guide/visa': typeof LangPublicGuideVisaRoute
  '/$lang/_public/hotels/search': typeof LangPublicHotelsSearchRoute
  '/$lang/_public/yacht/search': typeof LangPublicYachtSearchRoute
  '/$lang/_public/activities/': typeof LangPublicActivitiesIndexRoute
  '/$lang/_public/flights/': typeof LangPublicFlightsIndexRoute
  '/$lang/_public/guide/': typeof LangPublicGuideIndexRoute
  '/$lang/_public/hotels/': typeof LangPublicHotelsIndexRoute
  '/$lang/_public/rent-a-car/': typeof LangPublicRentACarIndexRoute
  '/$lang/_public/safari-tour/': typeof LangPublicSafariTourIndexRoute
  '/$lang/_public/tours/': typeof LangPublicToursIndexRoute
  '/$lang/_public/transfer/': typeof LangPublicTransferIndexRoute
  '/$lang/_public/yacht/': typeof LangPublicYachtIndexRoute
  '/$lang/_public/rent-a-car/select/$slug': typeof LangPublicRentACarSelectSlugRoute
  '/$lang/_public/rent-a-car/search/': typeof LangPublicRentACarSearchIndexRoute
  '/$lang/_public/rent-a-car/select/': typeof LangPublicRentACarSelectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/error'
    | '/$lang/not-found'
    | '/$lang/pending'
    | '/$lang/activities'
    | '/$lang/flights'
    | '/$lang/hotels'
    | '/$lang/rent-a-car'
    | '/$lang/yacht'
    | '/$lang/'
    | '/$lang/rent-a-car/search'
    | '/$lang/activities/search'
    | '/$lang/flights/search'
    | '/$lang/guide/bundles'
    | '/$lang/guide/hospitals'
    | '/$lang/guide/restaurants'
    | '/$lang/guide/sim-card'
    | '/$lang/guide/visa'
    | '/$lang/hotels/search'
    | '/$lang/yacht/search'
    | '/$lang/activities/'
    | '/$lang/flights/'
    | '/$lang/guide'
    | '/$lang/hotels/'
    | '/$lang/rent-a-car/'
    | '/$lang/safari-tour'
    | '/$lang/tours'
    | '/$lang/transfer'
    | '/$lang/yacht/'
    | '/$lang/rent-a-car/select/$slug'
    | '/$lang/rent-a-car/search/'
    | '/$lang/rent-a-car/select'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/error'
    | '/$lang/not-found'
    | '/$lang/pending'
    | '/$lang/activities/search'
    | '/$lang/flights/search'
    | '/$lang/guide/bundles'
    | '/$lang/guide/hospitals'
    | '/$lang/guide/restaurants'
    | '/$lang/guide/sim-card'
    | '/$lang/guide/visa'
    | '/$lang/hotels/search'
    | '/$lang/yacht/search'
    | '/$lang/activities'
    | '/$lang/flights'
    | '/$lang/guide'
    | '/$lang/hotels'
    | '/$lang/rent-a-car'
    | '/$lang/safari-tour'
    | '/$lang/tours'
    | '/$lang/transfer'
    | '/$lang/yacht'
    | '/$lang/rent-a-car/select/$slug'
    | '/$lang/rent-a-car/search'
    | '/$lang/rent-a-car/select'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_public'
    | '/$lang/error'
    | '/$lang/not-found'
    | '/$lang/pending'
    | '/$lang/_public/activities'
    | '/$lang/_public/flights'
    | '/$lang/_public/hotels'
    | '/$lang/_public/rent-a-car'
    | '/$lang/_public/yacht'
    | '/$lang/_public/'
    | '/$lang/_public/rent-a-car/search'
    | '/$lang/_public/activities/search'
    | '/$lang/_public/flights/search'
    | '/$lang/_public/guide/bundles'
    | '/$lang/_public/guide/hospitals'
    | '/$lang/_public/guide/restaurants'
    | '/$lang/_public/guide/sim-card'
    | '/$lang/_public/guide/visa'
    | '/$lang/_public/hotels/search'
    | '/$lang/_public/yacht/search'
    | '/$lang/_public/activities/'
    | '/$lang/_public/flights/'
    | '/$lang/_public/guide/'
    | '/$lang/_public/hotels/'
    | '/$lang/_public/rent-a-car/'
    | '/$lang/_public/safari-tour/'
    | '/$lang/_public/tours/'
    | '/$lang/_public/transfer/'
    | '/$lang/_public/yacht/'
    | '/$lang/_public/rent-a-car/select/$slug'
    | '/$lang/_public/rent-a-car/search/'
    | '/$lang/_public/rent-a-car/select/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/robots.txt': typeof RobotsDottxtServerRoute
  '/rss.xml': typeof RssDotxmlServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
}
export interface FileServerRoutesByTo {
  '/robots.txt': typeof RobotsDottxtServerRoute
  '/rss.xml': typeof RssDotxmlServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/robots.txt': typeof RobotsDottxtServerRoute
  '/rss.xml': typeof RssDotxmlServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/robots.txt' | '/rss.xml' | '/sitemap.xml'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/robots.txt' | '/rss.xml' | '/sitemap.xml'
  id: '__root__' | '/robots.txt' | '/rss.xml' | '/sitemap.xml'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  RobotsDottxtServerRoute: typeof RobotsDottxtServerRoute
  RssDotxmlServerRoute: typeof RssDotxmlServerRoute
  SitemapDotxmlServerRoute: typeof SitemapDotxmlServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/pending': {
      id: '/$lang/pending'
      path: '/pending'
      fullPath: '/$lang/pending'
      preLoaderRoute: typeof LangPendingRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/not-found': {
      id: '/$lang/not-found'
      path: '/not-found'
      fullPath: '/$lang/not-found'
      preLoaderRoute: typeof LangNotFoundRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/error': {
      id: '/$lang/error'
      path: '/error'
      fullPath: '/$lang/error'
      preLoaderRoute: typeof LangErrorRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_public': {
      id: '/$lang/_public'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangPublicRouteRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_public/': {
      id: '/$lang/_public/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangPublicIndexRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/yacht': {
      id: '/$lang/_public/yacht'
      path: '/yacht'
      fullPath: '/$lang/yacht'
      preLoaderRoute: typeof LangPublicYachtRouteRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/rent-a-car': {
      id: '/$lang/_public/rent-a-car'
      path: '/rent-a-car'
      fullPath: '/$lang/rent-a-car'
      preLoaderRoute: typeof LangPublicRentACarRouteRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/hotels': {
      id: '/$lang/_public/hotels'
      path: '/hotels'
      fullPath: '/$lang/hotels'
      preLoaderRoute: typeof LangPublicHotelsRouteRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/flights': {
      id: '/$lang/_public/flights'
      path: '/flights'
      fullPath: '/$lang/flights'
      preLoaderRoute: typeof LangPublicFlightsRouteRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/activities': {
      id: '/$lang/_public/activities'
      path: '/activities'
      fullPath: '/$lang/activities'
      preLoaderRoute: typeof LangPublicActivitiesRouteRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/yacht/': {
      id: '/$lang/_public/yacht/'
      path: '/'
      fullPath: '/$lang/yacht/'
      preLoaderRoute: typeof LangPublicYachtIndexRouteImport
      parentRoute: typeof LangPublicYachtRouteRoute
    }
    '/$lang/_public/transfer/': {
      id: '/$lang/_public/transfer/'
      path: '/transfer'
      fullPath: '/$lang/transfer'
      preLoaderRoute: typeof LangPublicTransferIndexRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/tours/': {
      id: '/$lang/_public/tours/'
      path: '/tours'
      fullPath: '/$lang/tours'
      preLoaderRoute: typeof LangPublicToursIndexRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/safari-tour/': {
      id: '/$lang/_public/safari-tour/'
      path: '/safari-tour'
      fullPath: '/$lang/safari-tour'
      preLoaderRoute: typeof LangPublicSafariTourIndexRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/rent-a-car/': {
      id: '/$lang/_public/rent-a-car/'
      path: '/'
      fullPath: '/$lang/rent-a-car/'
      preLoaderRoute: typeof LangPublicRentACarIndexRouteImport
      parentRoute: typeof LangPublicRentACarRouteRoute
    }
    '/$lang/_public/hotels/': {
      id: '/$lang/_public/hotels/'
      path: '/'
      fullPath: '/$lang/hotels/'
      preLoaderRoute: typeof LangPublicHotelsIndexRouteImport
      parentRoute: typeof LangPublicHotelsRouteRoute
    }
    '/$lang/_public/guide/': {
      id: '/$lang/_public/guide/'
      path: '/guide'
      fullPath: '/$lang/guide'
      preLoaderRoute: typeof LangPublicGuideIndexRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/flights/': {
      id: '/$lang/_public/flights/'
      path: '/'
      fullPath: '/$lang/flights/'
      preLoaderRoute: typeof LangPublicFlightsIndexRouteImport
      parentRoute: typeof LangPublicFlightsRouteRoute
    }
    '/$lang/_public/activities/': {
      id: '/$lang/_public/activities/'
      path: '/'
      fullPath: '/$lang/activities/'
      preLoaderRoute: typeof LangPublicActivitiesIndexRouteImport
      parentRoute: typeof LangPublicActivitiesRouteRoute
    }
    '/$lang/_public/yacht/search': {
      id: '/$lang/_public/yacht/search'
      path: '/search'
      fullPath: '/$lang/yacht/search'
      preLoaderRoute: typeof LangPublicYachtSearchRouteImport
      parentRoute: typeof LangPublicYachtRouteRoute
    }
    '/$lang/_public/hotels/search': {
      id: '/$lang/_public/hotels/search'
      path: '/search'
      fullPath: '/$lang/hotels/search'
      preLoaderRoute: typeof LangPublicHotelsSearchRouteImport
      parentRoute: typeof LangPublicHotelsRouteRoute
    }
    '/$lang/_public/guide/visa': {
      id: '/$lang/_public/guide/visa'
      path: '/guide/visa'
      fullPath: '/$lang/guide/visa'
      preLoaderRoute: typeof LangPublicGuideVisaRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/guide/sim-card': {
      id: '/$lang/_public/guide/sim-card'
      path: '/guide/sim-card'
      fullPath: '/$lang/guide/sim-card'
      preLoaderRoute: typeof LangPublicGuideSimCardRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/guide/restaurants': {
      id: '/$lang/_public/guide/restaurants'
      path: '/guide/restaurants'
      fullPath: '/$lang/guide/restaurants'
      preLoaderRoute: typeof LangPublicGuideRestaurantsRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/guide/hospitals': {
      id: '/$lang/_public/guide/hospitals'
      path: '/guide/hospitals'
      fullPath: '/$lang/guide/hospitals'
      preLoaderRoute: typeof LangPublicGuideHospitalsRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/guide/bundles': {
      id: '/$lang/_public/guide/bundles'
      path: '/guide/bundles'
      fullPath: '/$lang/guide/bundles'
      preLoaderRoute: typeof LangPublicGuideBundlesRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/flights/search': {
      id: '/$lang/_public/flights/search'
      path: '/search'
      fullPath: '/$lang/flights/search'
      preLoaderRoute: typeof LangPublicFlightsSearchRouteImport
      parentRoute: typeof LangPublicFlightsRouteRoute
    }
    '/$lang/_public/activities/search': {
      id: '/$lang/_public/activities/search'
      path: '/search'
      fullPath: '/$lang/activities/search'
      preLoaderRoute: typeof LangPublicActivitiesSearchRouteImport
      parentRoute: typeof LangPublicActivitiesRouteRoute
    }
    '/$lang/_public/rent-a-car/search': {
      id: '/$lang/_public/rent-a-car/search'
      path: '/search'
      fullPath: '/$lang/rent-a-car/search'
      preLoaderRoute: typeof LangPublicRentACarSearchRouteRouteImport
      parentRoute: typeof LangPublicRentACarRouteRoute
    }
    '/$lang/_public/rent-a-car/select/': {
      id: '/$lang/_public/rent-a-car/select/'
      path: '/select'
      fullPath: '/$lang/rent-a-car/select'
      preLoaderRoute: typeof LangPublicRentACarSelectIndexRouteImport
      parentRoute: typeof LangPublicRentACarRouteRoute
    }
    '/$lang/_public/rent-a-car/search/': {
      id: '/$lang/_public/rent-a-car/search/'
      path: '/'
      fullPath: '/$lang/rent-a-car/search/'
      preLoaderRoute: typeof LangPublicRentACarSearchIndexRouteImport
      parentRoute: typeof LangPublicRentACarSearchRouteRoute
    }
    '/$lang/_public/rent-a-car/select/$slug': {
      id: '/$lang/_public/rent-a-car/select/$slug'
      path: '/select/$slug'
      fullPath: '/$lang/rent-a-car/select/$slug'
      preLoaderRoute: typeof LangPublicRentACarSelectSlugRouteImport
      parentRoute: typeof LangPublicRentACarRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface LangPublicActivitiesRouteRouteChildren {
  LangPublicActivitiesSearchRoute: typeof LangPublicActivitiesSearchRoute
  LangPublicActivitiesIndexRoute: typeof LangPublicActivitiesIndexRoute
}

const LangPublicActivitiesRouteRouteChildren: LangPublicActivitiesRouteRouteChildren =
  {
    LangPublicActivitiesSearchRoute: LangPublicActivitiesSearchRoute,
    LangPublicActivitiesIndexRoute: LangPublicActivitiesIndexRoute,
  }

const LangPublicActivitiesRouteRouteWithChildren =
  LangPublicActivitiesRouteRoute._addFileChildren(
    LangPublicActivitiesRouteRouteChildren,
  )

interface LangPublicFlightsRouteRouteChildren {
  LangPublicFlightsSearchRoute: typeof LangPublicFlightsSearchRoute
  LangPublicFlightsIndexRoute: typeof LangPublicFlightsIndexRoute
}

const LangPublicFlightsRouteRouteChildren: LangPublicFlightsRouteRouteChildren =
  {
    LangPublicFlightsSearchRoute: LangPublicFlightsSearchRoute,
    LangPublicFlightsIndexRoute: LangPublicFlightsIndexRoute,
  }

const LangPublicFlightsRouteRouteWithChildren =
  LangPublicFlightsRouteRoute._addFileChildren(
    LangPublicFlightsRouteRouteChildren,
  )

interface LangPublicHotelsRouteRouteChildren {
  LangPublicHotelsSearchRoute: typeof LangPublicHotelsSearchRoute
  LangPublicHotelsIndexRoute: typeof LangPublicHotelsIndexRoute
}

const LangPublicHotelsRouteRouteChildren: LangPublicHotelsRouteRouteChildren = {
  LangPublicHotelsSearchRoute: LangPublicHotelsSearchRoute,
  LangPublicHotelsIndexRoute: LangPublicHotelsIndexRoute,
}

const LangPublicHotelsRouteRouteWithChildren =
  LangPublicHotelsRouteRoute._addFileChildren(
    LangPublicHotelsRouteRouteChildren,
  )

interface LangPublicRentACarSearchRouteRouteChildren {
  LangPublicRentACarSearchIndexRoute: typeof LangPublicRentACarSearchIndexRoute
}

const LangPublicRentACarSearchRouteRouteChildren: LangPublicRentACarSearchRouteRouteChildren =
  {
    LangPublicRentACarSearchIndexRoute: LangPublicRentACarSearchIndexRoute,
  }

const LangPublicRentACarSearchRouteRouteWithChildren =
  LangPublicRentACarSearchRouteRoute._addFileChildren(
    LangPublicRentACarSearchRouteRouteChildren,
  )

interface LangPublicRentACarRouteRouteChildren {
  LangPublicRentACarSearchRouteRoute: typeof LangPublicRentACarSearchRouteRouteWithChildren
  LangPublicRentACarIndexRoute: typeof LangPublicRentACarIndexRoute
  LangPublicRentACarSelectSlugRoute: typeof LangPublicRentACarSelectSlugRoute
  LangPublicRentACarSelectIndexRoute: typeof LangPublicRentACarSelectIndexRoute
}

const LangPublicRentACarRouteRouteChildren: LangPublicRentACarRouteRouteChildren =
  {
    LangPublicRentACarSearchRouteRoute:
      LangPublicRentACarSearchRouteRouteWithChildren,
    LangPublicRentACarIndexRoute: LangPublicRentACarIndexRoute,
    LangPublicRentACarSelectSlugRoute: LangPublicRentACarSelectSlugRoute,
    LangPublicRentACarSelectIndexRoute: LangPublicRentACarSelectIndexRoute,
  }

const LangPublicRentACarRouteRouteWithChildren =
  LangPublicRentACarRouteRoute._addFileChildren(
    LangPublicRentACarRouteRouteChildren,
  )

interface LangPublicYachtRouteRouteChildren {
  LangPublicYachtSearchRoute: typeof LangPublicYachtSearchRoute
  LangPublicYachtIndexRoute: typeof LangPublicYachtIndexRoute
}

const LangPublicYachtRouteRouteChildren: LangPublicYachtRouteRouteChildren = {
  LangPublicYachtSearchRoute: LangPublicYachtSearchRoute,
  LangPublicYachtIndexRoute: LangPublicYachtIndexRoute,
}

const LangPublicYachtRouteRouteWithChildren =
  LangPublicYachtRouteRoute._addFileChildren(LangPublicYachtRouteRouteChildren)

interface LangPublicRouteRouteChildren {
  LangPublicActivitiesRouteRoute: typeof LangPublicActivitiesRouteRouteWithChildren
  LangPublicFlightsRouteRoute: typeof LangPublicFlightsRouteRouteWithChildren
  LangPublicHotelsRouteRoute: typeof LangPublicHotelsRouteRouteWithChildren
  LangPublicRentACarRouteRoute: typeof LangPublicRentACarRouteRouteWithChildren
  LangPublicYachtRouteRoute: typeof LangPublicYachtRouteRouteWithChildren
  LangPublicIndexRoute: typeof LangPublicIndexRoute
  LangPublicGuideBundlesRoute: typeof LangPublicGuideBundlesRoute
  LangPublicGuideHospitalsRoute: typeof LangPublicGuideHospitalsRoute
  LangPublicGuideRestaurantsRoute: typeof LangPublicGuideRestaurantsRoute
  LangPublicGuideSimCardRoute: typeof LangPublicGuideSimCardRoute
  LangPublicGuideVisaRoute: typeof LangPublicGuideVisaRoute
  LangPublicGuideIndexRoute: typeof LangPublicGuideIndexRoute
  LangPublicSafariTourIndexRoute: typeof LangPublicSafariTourIndexRoute
  LangPublicToursIndexRoute: typeof LangPublicToursIndexRoute
  LangPublicTransferIndexRoute: typeof LangPublicTransferIndexRoute
}

const LangPublicRouteRouteChildren: LangPublicRouteRouteChildren = {
  LangPublicActivitiesRouteRoute: LangPublicActivitiesRouteRouteWithChildren,
  LangPublicFlightsRouteRoute: LangPublicFlightsRouteRouteWithChildren,
  LangPublicHotelsRouteRoute: LangPublicHotelsRouteRouteWithChildren,
  LangPublicRentACarRouteRoute: LangPublicRentACarRouteRouteWithChildren,
  LangPublicYachtRouteRoute: LangPublicYachtRouteRouteWithChildren,
  LangPublicIndexRoute: LangPublicIndexRoute,
  LangPublicGuideBundlesRoute: LangPublicGuideBundlesRoute,
  LangPublicGuideHospitalsRoute: LangPublicGuideHospitalsRoute,
  LangPublicGuideRestaurantsRoute: LangPublicGuideRestaurantsRoute,
  LangPublicGuideSimCardRoute: LangPublicGuideSimCardRoute,
  LangPublicGuideVisaRoute: LangPublicGuideVisaRoute,
  LangPublicGuideIndexRoute: LangPublicGuideIndexRoute,
  LangPublicSafariTourIndexRoute: LangPublicSafariTourIndexRoute,
  LangPublicToursIndexRoute: LangPublicToursIndexRoute,
  LangPublicTransferIndexRoute: LangPublicTransferIndexRoute,
}

const LangPublicRouteRouteWithChildren = LangPublicRouteRoute._addFileChildren(
  LangPublicRouteRouteChildren,
)

interface LangRouteChildren {
  LangPublicRouteRoute: typeof LangPublicRouteRouteWithChildren
  LangErrorRoute: typeof LangErrorRoute
  LangNotFoundRoute: typeof LangNotFoundRoute
  LangPendingRoute: typeof LangPendingRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangPublicRouteRoute: LangPublicRouteRouteWithChildren,
  LangErrorRoute: LangErrorRoute,
  LangNotFoundRoute: LangNotFoundRoute,
  LangPendingRoute: LangPendingRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  RobotsDottxtServerRoute: RobotsDottxtServerRoute,
  RssDotxmlServerRoute: RssDotxmlServerRoute,
  SitemapDotxmlServerRoute: SitemapDotxmlServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
